import 'vuetify/styles'
import { createVuetify } from 'vuetify'

import { aliases, mdi } from 'vuetify/iconsets/mdi'
import { aliases as mdAliases, md } from 'vuetify/iconsets/md'
import { aliases as fontAwesomeAliases, fa } from 'vuetify/iconsets/fa'

import VTagItem from './components/tags/VTagItem.vue'
import TagFab from '@/components/fabs/TagFab.vue'
import EvTagTray from '@/components/tags/EvTagTray.vue'
import EvTrayCard from '@/components/tags/EvTrayCard.vue'

import DiceFab from '@/components/fabs/DiceFab.vue'
import AvatarFab from '@/components/fabs/AvatarFab.vue'

import myCustomTheme from '@/themes/myCustomTheme'

import {
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAppBarTitle,
  VToolbar,
  VToolbarTitle,
  VContainer,
  VMain,
  VLayout,
  VResponsive,
  VNavigationDrawer,
  VList,
  VListItem,
  VForm,
  VTextarea,
  VTable,
  VFileInput,
  VRow,
  VCol,
  VTextField,
  VImg,
  VBtn,
  VBtnToggle,
  VAvatar,
  VBadge,
  VIcon,
  VCard,
  VCardItem,
  VCardTitle,
  VCardSubtitle,
  VCardText,
  VCardActions,
  VSheet,
  VDialog,
  VCheckbox,
  VSpacer,
  VDivider,
  VFooter,
  VBottomSheet,
  VChip,
  VChipGroup,
  VSelect,
  VAutocomplete,
  VItem,
  VItemGroup,
  VTooltip,
  VColorPicker,
  VLabel,
  VHover,
  VFab,
  VBottomNavigation,
  VTimeline,
  VTimelineItem,
  VStepper,
  VStepperActions,
  VStepperHeader,
  VStepperItem,
  VStepperWindow,
  VStepperWindowItem,
  VSpeedDial,
  VSystemBar,
  VScaleTransition,
  VFadeTransition,
  VFabTransition,
  VExpandXTransition,
  VSlideXTransition,
  VSnackbar,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelText,
  VExpansionPanelTitle,
} from 'vuetify/components'
import {
  VStepperVerticalActions,
  VStepperVerticalItem,
  VSnackbarQueue,
} from 'vuetify/labs/components'

export const vuetify = createVuetify({
  theme: {
    defaultTheme: 'myCustomTheme',
    themes: {
      myCustomTheme,
    },
  },
  icons: {
    defaultSet: 'mdi', // 'mdi' is Material Design Icons; use 'md' for Material Icons
    aliases: {
      ...fontAwesomeAliases,
      ...mdAliases,
      ...aliases,
      tag: 'mdi-tag',
      'no-tag': 'mdi-tag-outline',
      tags: 'mdi-tag-multiple',
      'no-tags': 'mdi-tag-multiple-outline',
      'tag-add': 'mdi-tag-plus',
      event: 'mdi-timeline',
      'no-event': 'mdi-timeline-outline',
      events: 'mdi-calendar-clock',
      'no-events': 'mdi-calendar-clock-outline',
      swatches: 'mdi-palette-swatch',
      'no-swatches': 'mdi-palette-swatch-outline',
      dropper: 'mdi-eyedropper',
      'no-dropper': 'mdi-eyedropper-off',
      timestamp: 'mdi-web-clock',
      system: 'mdi-code-braces',

      dice: 'mdi-dice-multiple',
      'no-dice': 'mdi-dice-multiple-outline',
      d20: 'mdi-dice-d20',
      d12: 'mdi-dice-d12',
      d10: 'mdi-dice-d10',
      d8: 'mdi-dice-d8',
      d6: 'mdi-dice-d6',
      d4: 'mdi-dice-d4',

      challenge: 'mdi-hazard-lights',

      id: 'mdi-account-box-outline',
      name: 'mdi-account-circle-outline',
      space: 'mdi-tag-multiple-outline',
      palette: 'mdi-palette',
      color: 'mdi-circle-opacity',
      date: 'mdi-web-clock',

      home: 'mdi-home',
      icon: 'mdi-label-variant-outline',
      next: 'mdi-arrow-right',
      delete: 'mdi-delete',
      'delete-off': 'mdi-delete-outline',
      clear: 'mdi-close',
      close: 'mdi-close',
      upvote: 'mdi-arrow-up-bold',
      'upvote-off': 'mdi-arrow-up-bold-outline',
      downvote: 'mdi-arrow-down-bold',
      'downvote-off': 'mdi-arrow-down-bold-outline',
      comment: 'mdi-comment',
      'comment-off': 'mdi-comment-outline',
      favorite: 'mdi-heart',
      'favorite-off': 'mdi-heart-outline',
      share: 'mdi-share',
      addTag: 'mdi-tag-plus',
      removetag: 'mdi-tag-remove',
      'removetag-off': 'mdi-tag-remove-outline',

      primary: 'mdi-cards-spade',
      secondary: 'mdi-cards-heart',
      tertiary: 'mdi-cards-club',
      quaternary: 'mdi-cards-diamond',

      wormhole: 'mdi-atom-variant',
      scarf: '🧣',
      'persona-name': 'mdi-account-circle',

      'sta-attribute': 'md:edit_attributes',
      'sta-department': 'md:toggle_off',

      'sta-trait': 'mdi-star-four-points-outline',
      'sta-talent': 'mdi-star-four-points',
      'sta-value': 'mdi-star-four-points-small',
      'sta-focus': 'mdi-image-filter-center-focus',

      'sta-control': 'mdi-image-filter-center-focus-strong',
      'sta-daring': 'mdi-octagram',
      'sta-fitness': 'mdi-heart-pulse',
      'sta-presence': 'mdi-account-multiple',
      'sta-insight': 'mdi-head-snowflake',
      'sta-reason': 'mdi-brain',

      'sta-command': 'mdi-account-group',
      'sta-conn': 'mdi-gamepad',
      'sta-engineering': 'mdi-wrench',
      'sta-security': 'mdi-shield-account',
      'sta-medicine': 'mdi-hospital-box',
      'sta-science': 'mdi-atom-variant',

      'sta-species': 'mdi-account-box',
      'sta-environment': 'mdi-earth-box',
      'sta-upbringing': 'mdi-home-account',
      'sta-career': 'mdi-map-marker-path',
      'sta-experience': 'mdi-note-edit',
      'sta-event': 'mdi-note-edit',

      'sta-stepone': 'mdi-account-box',
      'sta-steptwo': 'mdi-earth-box',
      'sta-stepthree': 'mdi-home-account',
      'sta-stepfour': 'mdi-map-marker-path',
      'sta-stepfive': 'mdi-note-edit',
      'sta-stepsix': 'mdi-calendar-account',
      'sta-stepseven': 'mdi-checkbox-multiple-marked',
    },
    sets: {
      mdi,
      md,
      fa,
    },
  },
  defaults: {
    VLayout: {
      class: 'bg-transparent',
    },
    VFooter: {
      class: 'bg-surface pb-16',
    },
    VTooltip: {
      location: 'top',
      contentClass: 'bg-surface ma-2 pa-3',
    },
    VBottomNavigation: {},
    VNavigationDrawer: {
      class: 'bg-background',
    },
    VBottomSheet: {},
    VBtn: {},
    VBtnToggle: {
      density: 'compact',
      size: 'small',
      variant: 'plain',
    },
    VSystemBar: {
      class: 'bg-transparent border-opacity-25 border-t-md border-primary',
      VBtn: {
        density: 'compact',
        size: 'small',
        ripple: false,
        variant: 'plain',
      },
    },
    VCard: {},
    VCardActions: {
      VBtn: {
        density: 'compact',
        size: 'small',
        ripple: false,
        variant: 'plain',
      },
      VSheet: {
        class: 'bg-transparent',
      },
    },
    VCardText: {
      class: 'ma-0 pb-0 px-0',
      VBtnToggle: {
        color: 'text',
        density: 'compact',
        size: 'small',
        variant: 'plain',
      },
    },

    VChipGroup: {
      variant: 'text',
      VChip: {
        variant: 'text',
        class: 'rounded',
        tile: true,
        closeIcon: 'mdi-close',
      },
    },

    VSnackbar: {
      timeout: 4000,
      color: 'surface',
      location: 'bottom end',
      VCard: {
        class: 'ma-0 pa-0 elevation-0',
      },
    },
    VLabel: {
      class: 'text-uppercase text-disabled text-caption	',
    },
  },
  components: {
    EvTagTray,
    EvTrayCard,
    VTagItem,
    TagFab,
    DiceFab,
    AvatarFab,
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAppBarTitle,
    VToolbar,
    VToolbarTitle,
    VContainer,
    VMain,
    VLayout,
    VResponsive,
    VBottomNavigation,
    VNavigationDrawer,
    VList,
    VListItem,
    VForm,
    VTextarea,
    VTable,
    VFileInput,
    VRow,
    VCol,
    VTextField,
    VImg,
    VCard,
    VCardItem,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VSheet,
    VIcon,
    VBtn,
    VBtnToggle,
    VAvatar,
    VBadge,
    VDialog,
    VSelect,
    VAutocomplete,
    VCheckbox,
    VSpacer,
    VDivider,
    VBottomSheet,
    VFooter,
    VChip,
    VChipGroup,
    VItem,
    VItemGroup,
    VTooltip,
    VColorPicker,
    VLabel,
    VHover,
    VFab,
    VTimeline,
    VTimelineItem,
    VStepper,
    VStepperActions,
    VStepperHeader,
    VStepperItem,
    VStepperWindow,
    VStepperWindowItem,
    VStepperVerticalActions,
    VStepperVerticalItem,
    VSpeedDial,
    VSystemBar,
    VScaleTransition,
    VFadeTransition,
    VFabTransition,
    VExpandXTransition,
    VSlideXTransition,
    VSnackbar,
    VExpansionPanel,
    VExpansionPanels,
    VExpansionPanelText,
    VExpansionPanelTitle,
    VSnackbarQueue,
  },
})
